#include "TexturesX.h"

// this file has been auto-generated by rescompiler. do not hand-edit

const CompiledResInfo Textures::ResIndex[3] =
{
	{ 0, "texture", "gameselect_mode_battle", "GAMESELECT_MODE_BATTLE" },
	{ 0, "texture", "gameselect_mode_classic", "GAMESELECT_MODE_CLASSIC" },
	{ 0, "texture", "gameselect_mode_surviver", "GAMESELECT_MODE_SURVIVER" },
};
