#pragma once

// this file has been auto-generated by rescompiler. do not hand-edit

#include "ResIndex.h"

namespace Textures
{
	const static int GAMEOVER_HINT_BACK = 0;
	const static int GAMEVIEW_UPGRADE = 1;
	const static int GAMEVIEW_UPGRADE_BACK = 2;
	const static int GAMEVIEW_UPGRADE_BACK2 = 3;
	const static int OPTIONSVIEW_GAMEPAD = 4;
	const static int OPTIONSVIEW_VOLUME = 5;
	const static int UPGRADEBOUGHT_LASER = 6;
	const static int UPGRADEBOUGHT_PATROL = 7;
	const static int UPGRADEBOUGHT_SHOCK = 8;
	const static int UPGRADEBOUGHT_SPECIAL = 9;
	const static int UPGRADEBOUGHT_VULCAN = 10;
	const static int UPGRADE_BACK = 11;
	const static int UPGRADE_OVERLAY = 12;
	const extern CompiledResInfo ResIndex[13];
};
