#pragma once

// this file has been auto-generated by rescompiler. do not hand-edit

#include "ResIndex.h"

namespace Textures
{
	const static int GAMESELECT_MODE_BATTLE = 0;
	const static int GAMESELECT_MODE_CLASSIC = 1;
	const static int GAMESELECT_MODE_SURVIVER = 2;
	const extern CompiledResInfo ResIndex[3];
};
