#include "TexturesX.h"

// this file has been auto-generated by rescompiler. do not hand-edit

const CompiledResInfo Textures::ResIndex[13] =
{
	{ 0, "texture", "gameover_hint_back", "GAMEOVER_HINT_BACK" },
	{ 0, "texture", "gameview_upgrade", "GAMEVIEW_UPGRADE" },
	{ 0, "texture", "gameview_upgrade_back", "GAMEVIEW_UPGRADE_BACK" },
	{ 0, "texture", "gameview_upgrade_back2", "GAMEVIEW_UPGRADE_BACK2" },
	{ 0, "texture", "optionsview_gamepad", "OPTIONSVIEW_GAMEPAD" },
	{ 0, "texture", "optionsview_volume", "OPTIONSVIEW_VOLUME" },
	{ 0, "texture", "upgradebought_laser", "UPGRADEBOUGHT_LASER" },
	{ 0, "texture", "upgradebought_patrol", "UPGRADEBOUGHT_PATROL" },
	{ 0, "texture", "upgradebought_shock_v2", "UPGRADEBOUGHT_SHOCK" },
	{ 0, "texture", "upgradebought_special_v2", "UPGRADEBOUGHT_SPECIAL" },
	{ 0, "texture", "upgradebought_vulcan", "UPGRADEBOUGHT_VULCAN" },
	{ 0, "texture", "upgrade_back", "UPGRADE_BACK" },
	{ 0, "texture", "upgrade_overlay", "UPGRADE_OVERLAY" },
};
