language: cpp
sudo: required
dist: xenial

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake --version;
      sudo apt-get install -y --no-install-recommends libsdl2-dev;
      sudo apt-get install -y --no-install-recommends libglew-dev;
      sudo apt-get install -y --no-install-recommends libgtk2.0-dev;
      sudo apt-get install -y --no-install-recommends libfreeimage-dev;
      sudo apt-get install -y --no-install-recommends libfreetype6-dev;
      sudo apt-get install -y --no-install-recommends libavcodec-dev;
      sudo apt-get install -y --no-install-recommends libavdevice-dev;
      sudo apt-get install -y --no-install-recommends libavfilter-dev;
      sudo apt-get install -y --no-install-recommends libavformat-dev;
      sudo apt-get install -y --no-install-recommends libavresample-dev;
      sudo apt-get install -y --no-install-recommends libswscale-dev;
      sudo apt-get install -y --no-install-recommends libturbojpeg0-dev;
      sudo apt-get install -y --no-install-recommends gobjc++;
      sudo apt-get install -y --no-install-recommends libusb-1.0-0-dev;
      sudo apt-get install -y --no-install-recommends libasound2-dev;
      sudo apt-get install -y --no-install-recommends portaudio19-dev;
      sudo apt-get install -y --no-install-recommends ocl-icd-opencl-dev;
    fi

script: 
  - git submodule update --init --recursive
  - ./build.sh
  - echo add_root users/marcel >> chibi-root.txt 
  - ./build.sh
