language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script: 
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y --no-install-recommends libglew-dev;
      sudo apt-get install -y --no-install-recommends libfreeimage-dev;
    fi
  - git submodule update --init --recursive
  - ./build.sh
