language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    
before_install:
  # the version of portaudio that's included with Debian is outdated.
  # portaudio needs to be built from sources on Linux.
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake --version;
      sudo apt-get install -y --no-install-recommends libgtk2.0-dev;
      sudo apt-get install -y --no-install-recommends libglew-dev;
      sudo apt-get install -y --no-install-recommends libfreeimage-dev;
      sudo apt-get install -y --no-install-recommends libsdl2-dev;
      wget http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz;
      tar -xf pa_stable_v190600_20161030.tgz;
      cd portaudio;
      cmake -DCMAKE_BUILD_TYPE=Release .;
      sudo make install;
      cd ..;
      sudo apt-get install libavcodec-dev;
      sudo apt-get install libavdevice-dev;
      sudo apt-get install libavfilter-dev;
      sudo apt-get install libavformat-dev;
      sudo apt-get install libswscale-dev;
      sudo apt-get install libturbojpeg0-dev;
      sudo apt-get install gobjc++;
      sudo apt-get install libusb-1.0-0-dev;
    fi

script: 
  - git submodule update --init --recursive
  - ./build.sh
