language: cpp
sudo: required
dist: xenial

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libsdl2-dev
      - libglew-dev
      - libgtk2.0-dev
      - libfreeimage-dev
      - libfreetype6-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libswscale-dev
      - libturbojpeg0-dev
      - gobjc++
      - libusb-1.0-0-dev
      - libasound2-dev
      - portaudio19-dev

compiler:
  - gcc
  - clang

script: 
  - git submodule update --init --recursive
  - ./build.sh
