#pragma once

#ifdef DEBUG
	#define ITCHIO_BUILD 0
	#define DEPLOY_BUILD 0
#else
	#define ITCHIO_BUILD 1
	#define DEPLOY_BUILD 0
#endif

#if DEPLOY_BUILD
	#define PUBLIC_DEMO_BUILD 0
	#define ENABLE_NETWORKING 1
	#define ENABLE_NETWORKING_DEBUGS 1
	#define ENABLE_NETWORKING_DISCOVERY 0
	#define ENABLE_OPTIONS 0
	#define ENABLE_DEVMODE 0
	#define ENABLE_STEAM 1
#elif ITCHIO_BUILD
	#define PUBLIC_DEMO_BUILD 1
	#define ENABLE_NETWORKING 1
	#define ENABLE_NETWORKING_DEBUGS 1
	#define ENABLE_NETWORKING_DISCOVERY 0
	#define ENABLE_OPTIONS 1
	#define ENABLE_DEVMODE 1
	#define ENABLE_STEAM 1
#else
	#define PUBLIC_DEMO_BUILD 0
	#define ENABLE_NETWORKING 1
	#define ENABLE_NETWORKING_DEBUGS 1
	#define ENABLE_NETWORKING_DISCOVERY 0
	#define ENABLE_OPTIONS 1
	#define ENABLE_DEVMODE 1
	#define ENABLE_STEAM 1
#endif

#if ITCHIO_BUILD
	#define ITCHIO_SHOW_URLS 0
	#define ITCHIO_SHOW_KICKSTARTER 0
	#define ITCHIO_SHOW_BANNER 0
#else
	#define ITCHIO_SHOW_URLS 0
	#define ITCHIO_SHOW_KICKSTARTER 0
	#define ITCHIO_SHOW_BANNER 0
#endif

#if !DEPLOY_BUILD && !PUBLIC_DEMO_BUILD
	#define DEBUG_RANDOM_CALLSITES 0
	#define ENABLE_GAMESTATE_DESYNC_DETECTION 1
	#define ENABLE_GAMESTATE_CRC_LOGGING (ENABLE_GAMESTATE_DESYNC_DETECTION && 1)
#else
	#define DEBUG_RANDOM_CALLSITES 0 // do not alter
	#define ENABLE_GAMESTATE_DESYNC_DETECTION 0 // do not alter
	#define ENABLE_GAMESTATE_CRC_LOGGING 0 // do not alter
#endif
