VECCOMPILE = ../../../prototypes/vecrend/veccompile -q 9
RESOURCES = ../../Resources/
RESOURCES_SRC = ../Resources/

SRC_VEC = \
	gauge_button_less_0.vg \
	gauge_button_less_1.vg \
	gauge_button_more_0.vg \
	gauge_button_more_1.vg \
	indicator_circle.vg \
	indicator_tick.vg \
	layer0.vg \
	layer1.vg \
	layer_hidden.vg \
	magic_brushsize.vg \
	magic_main.vg \
	magic_tooltype.vg \
	magic_zoom.vg \
	eyedropper.vg \
	indicator_circle.vg \
	pivot.vg

.PHONY : dummy

DST_VEC = $(SRC_VEC:.vg=.vgc)

all : $(DST_VEC)
	cp gauge_button_less_0.vgc.png $(RESOURCES)gauge_button_less_0.png
	cp gauge_button_less_0@2x.vgc.png $(RESOURCES)gauge_button_less_0@2x.png
	cp gauge_button_less_1.vgc.png $(RESOURCES)gauge_button_less_1.png
	cp gauge_button_less_1@2x.vgc.png $(RESOURCES)gauge_button_less_1@2x.png
	cp gauge_button_more_0.vgc.png $(RESOURCES)gauge_button_more_0.png
	cp gauge_button_more_0@2x.vgc.png $(RESOURCES)gauge_button_more_0@2x.png
	cp gauge_button_more_1.vgc.png $(RESOURCES)gauge_button_more_1.png
	cp gauge_button_more_1@2x.vgc.png $(RESOURCES)gauge_button_more_1@2x.png
	cp layer0.vgc.png $(RESOURCES)layer0.png
	cp layer0@2x.vgc.png $(RESOURCES)layer0@2x.png
	cp layer1.vgc.png $(RESOURCES)layer1.png
	cp layer1@2x.vgc.png $(RESOURCES)layer1@2x.png
	cp layer_hidden.vgc.png $(RESOURCES)layer_hidden.png
	cp layer_hidden@2x.vgc.png $(RESOURCES)layer_hidden@2x.png
	cp magic_brushsize.vgc.png $(RESOURCES)magic_brushsize.png
	cp magic_brushsize@2x.vgc.png $(RESOURCES)magic_brushsize@2x.png
	cp magic_main.vgc.png $(RESOURCES)magic_main.png
	cp magic_main@2x.vgc.png $(RESOURCES)magic_main@2x.png
	cp magic_tooltype.vgc.png $(RESOURCES)magic_tooltype.png
	cp magic_tooltype@2x.vgc.png $(RESOURCES)magic_tooltype@2x.png
	cp magic_zoom.vgc.png $(RESOURCES)magic_zoom.png
	cp magic_zoom@2x.vgc.png $(RESOURCES)magic_zoom@2x.png
	cp eyedropper.vgc.png $(RESOURCES)eyedropper.png
	cp eyedropper@2x.vgc.png $(RESOURCES)eyedropper@2x.png
	cp indicator_circle.vgc.png $(RESOURCES)indicator_circle.png
	cp indicator_circle@2x.vgc.png $(RESOURCES)indicator_circle@2x.png
	cp indicator_tick.vgc.png $(RESOURCES)indicator_tick.png
	cp indicator_tick@2x.vgc.png $(RESOURCES)indicator_tick@2x.png
	cp pivot.vgc.png $(RESOURCES)pivot.png
	cp pivot@2x.vgc.png $(RESOURCES)pivot@2x.png
	
	cp $(RESOURCES_SRC)back_dark_pattern.png $(RESOURCES)
	cp $(RESOURCES_SRC)back_pattern.png $(RESOURCES)
	cp $(RESOURCES_SRC)back_pattern@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_done.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_help.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_help@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_layer_fill.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_layer_fill@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_layer_merge.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_layer_merge@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_layers.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_layers@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_new.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_new@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_redo.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_redo@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_serve.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_serve@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_share.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_share@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_tool.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_tool@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_undo.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_undo@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_visibility.png $(RESOURCES)
	cp $(RESOURCES_SRC)button_visibility@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)colorwheel.png $(RESOURCES)
	cp $(RESOURCES_SRC)colorwheel@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)crosshair_large.png $(RESOURCES)
	cp $(RESOURCES_SRC)crosshair_medium.png $(RESOURCES)
	cp $(RESOURCES_SRC)crosshair_small.png $(RESOURCES)
#	cp $(RESOURCES_SRC)fbicon.png $(RESOURCES)
	cp $(RESOURCES_SRC)gauge_back.png $(RESOURCES)
	cp $(RESOURCES_SRC)gauge_back@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)Icon.png $(RESOURCES)
	cp $(RESOURCES_SRC)Icon@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)Icon_iPad.png $(RESOURCES)
	cp $(RESOURCES_SRC)iTunesArtwork.jpg $(RESOURCES)
	cp $(RESOURCES_SRC)magic_glow.png $(RESOURCES)
	cp $(RESOURCES_SRC)menu_indicator.png $(RESOURCES)
	cp $(RESOURCES_SRC)pattern_select_back.png $(RESOURCES)
	cp $(RESOURCES_SRC)pattern_select_back@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_00.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_01.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_02.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_10.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_11.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_12.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_20.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_21.png $(RESOURCES)
	cp $(RESOURCES_SRC)images/shadow_22.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_brush.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_brush@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_brush_sel.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_brush_sel@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_eraser.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_eraser@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_eraser_sel.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_eraser_sel@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_smudge.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_smudge@2x.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_smudge_sel.png $(RESOURCES)
	cp $(RESOURCES_SRC)tool_smudge_sel@2x.png $(RESOURCES)

%.vgc : %.vg dummy
	$(VECCOMPILE) -c $< -o $@ -q 9
	$(VECCOMPILE) -c $< -o $(@:.vgc=\@2x.vgc) -q 9 -s 2
