#pragma once

enum PROTOCOLS
{
	PROTOCOL_CHANNEL = 1,
	PROTOCOL_RPC = 2,
	PROTOCOL_CUSTOM = 8
};

#define CHANNELMSG_TRUNK          1
#define CHANNELMSG_CONNECT        2
#define CHANNELMSG_CONNECT_OK     3
#define CHANNELMSG_CONNECT_ERROR  4
#define CHANNELMSG_CONNECT_ACK    5
#define CHANNELMSG_DISCONNECT     6
#define CHANNELMSG_DISCONNECT_ACK 7
#define CHANNELMSG_PING           8
#define CHANNELMSG_PONG           9
#define CHANNELMSG_RT_UPDATE      10
#define CHANNELMSG_RT_ACK         11
#define CHANNELMSG_RT_NACK        12
#define CHANNELMSG_UNPACK         13
