#include "fluidCube2d.h"
#include <math.h>
#include <string.h>

/*
https://mikeash.com/pyblog/fluid-simulation-for-dummies.html
Coding Challenge #132: Fluid Simulation
https://www.youtube.com/watch?v=alhpH6ECFvQ
*/

/*

todo : expperiment with the following boundary modes, and external forces,
from: http://karlsims.com/fluid-flow.html,

Zero: using a value of zero beyond the grid will avoid flow toward or away from the boundary, as if the fluid is contained in a box, because any edge cell's component of flow normal to the boundary would typically create a non-zero divergence and be removed. The divergence-removal examples above used this mode.
Repeat: repeating the flow value from the nearest edge cell will instead allow flow toward or away from the edges as if the fluid can exit or enter the grid.
Scaled repeat: combining zero and repeat edge-modes can also be useful. Using a scaled value of the nearest edge cell can give a soft boundary effect that slows down the flow at the edges but doesn't completely stop it. Alternatively, using zero for the flow component normal to the boundary, and repeat mode for the component parallel to the boundary, can give a more slippery edge effect.
Wrap: copying the flow value from the opposite side of the grid can create a wrap-around behavior where flow exiting on one side of the grid enters on the other.

Obstacles can also be added to the grid with similar boundary conditions by forcing the flow, or its normal component, to zero at their locations.

--

Realistic looking fluid behavior can be generated by alternating between the fluid momentum and divergence-removal steps described above. However some non-zero flow velocity needs to be set somehow, either procedurally or interactively. For example, adding linear flow at specific locations can create a squirting ink effect (see below), or tracking mouse or camera motion can be used to interactively push the fluid.

Other forces can be added to simulate various physical phenomena:

Gravity or buoyency can affect some parts of the fluid differently than others using a tracer image that represents the fluid density.
Damping or friction can reduce the flow velocity over time.
Viscosity can be simulated by diffusing the flow field slightly at each time step so the velocities become more like their neighbors. Note that the repeated resampling of the flow field will also cause a small amount of diffusion.
Cohesive forces can be approximated by using a tracer image to track different fluid substances, such as oil vs water, and then pushing the substances toward areas of the same type, moving convex boundaries inwards and concave boundaries outwards.

*/

#define IX_2D(x, y) ((x) + (y) * sizeX)

static void set_bnd2d(const int b, float * x, const int sizeX, const int sizeY)
{
	for (int i = 1; i < sizeX - 1; ++i)
	{
		x[IX_2D(i, 0      )] = b == 2 ? -x[IX_2D(i, 1      )] : x[IX_2D(i, 1      )];
		x[IX_2D(i, sizeY-1)] = b == 2 ? -x[IX_2D(i, sizeY-2)] : x[IX_2D(i, sizeY-2)];
	}
	
	for (int j = 1; j < sizeY - 1; ++j)
	{
		x[IX_2D(0      , j)] = b == 1 ? -x[IX_2D(1      , j)] : x[IX_2D(1      , j)];
		x[IX_2D(sizeX-1, j)] = b == 1 ? -x[IX_2D(sizeX-2, j)] : x[IX_2D(sizeX-2, j)];
	}

    x[IX_2D(0,             0)]   = 0.5f * (x[IX_2D(1,             0)] + x[IX_2D(0,             1)]);
    x[IX_2D(0,       sizeY-1)]   = 0.5f * (x[IX_2D(1,       sizeY-1)] + x[IX_2D(0,       sizeY-2)]);
    x[IX_2D(sizeX-1,       0)]   = 0.5f * (x[IX_2D(sizeX-2,       0)] + x[IX_2D(sizeX-1,       1)]);
    x[IX_2D(sizeX-1, sizeY-1)]   = 0.5f * (x[IX_2D(sizeX-2, sizeY-1)] + x[IX_2D(sizeX-1, sizeY-2)]);
}

static void lin_solve2d(const int b, float * __restrict x, const float * __restrict x0, const float a, const float c, const int iter, const int sizeX, const int sizeY)
{
    const float cRecip = 1.f / c;

// todo : we're updating x[] inside the loop while also reading from it. this doesn't seem right

    for (int k = 0; k < iter; ++k)
    {
		for (int j = 1; j < sizeY - 1; ++j)
		{
			const int index = IX_2D(0, j);
			
			const float * __restrict x0_line = x0 + index;
			      float * __restrict x_line  = x  + index;
			
			float prev_x = x_line[0];
			
			for (int i = 1; i < sizeX - 1; ++i)
			{
			#if 0
				x_line[i] = (x0_line[i] + a * (x_line[i - 1] + x_line[i + 1] + x_line[i - sizeX] + x_line[i + sizeX])) * cRecip;
			#elif 1
				const float curr_x = x_line[i];
				
				x_line[i] = (x0_line[i] + a * ((prev_x + x_line[i + 1]) + (x_line[i - sizeX] + x_line[i + sizeX]))) * cRecip;
				
				prev_x = curr_x;
			#else
				// note : we keep this verion around since it's easier to port to a shader
				x[IX_2D(i, j)] =
					(
						x0[IX_2D(i, j)]
						+ a *
							(
								+x[IX_2D(i+1, j  )]
								+x[IX_2D(i-1, j  )]
								+x[IX_2D(i  , j+1)]
								+x[IX_2D(i  , j-1)]
							)
					) * cRecip;
			#endif
			}
		}

        set_bnd2d(b, x, sizeX, sizeY);
    }
}

static void lin_solve2d_xy(
	float * __restrict x, const float * __restrict x0,
	float * __restrict y, const float * __restrict y0,
	const float a, const float c, const int iter, const int sizeX, const int sizeY)
{
    const float cRecip = 1.f / c;

// todo : we're updating x[] inside the loop while also reading from it. this doesn't seem right

    for (int k = 0; k < iter; ++k)
    {
		for (int j = 1; j < sizeY - 1; ++j)
		{
			const int index = IX_2D(0, j);
			
			const float * __restrict x0_line = x0 + index;
			      float * __restrict x_line  = x  + index;
			
			const float * __restrict y0_line = y0 + index;
			      float * __restrict y_line  = y  + index;
			
			float prev_x = x_line[0];
			float prev_y = y_line[0];
			
			for (int i = 1; i < sizeX - 1; ++i)
			{
			#if 0
				x_line[i] = (x0_line[i] + a * (x_line[i - 1] + x_line[i + 1] + x_line[i - sizeX] + x_line[i + sizeX])) * cRecip;
				y_line[i] = (y0_line[i] + a * (y_line[i - 1] + y_line[i + 1] + y_line[i - sizeX] + y_line[i + sizeX])) * cRecip;
			#else
				const float curr_x = x_line[i];
				const float curr_y = y_line[i];
				
				x_line[i] = (x0_line[i] + a * ((prev_x + x_line[i + 1]) + (x_line[i - sizeX] + x_line[i + sizeX]))) * cRecip;
				y_line[i] = (y0_line[i] + a * ((prev_y + y_line[i + 1]) + (y_line[i - sizeX] + y_line[i + sizeX]))) * cRecip;
				
				prev_x = curr_x;
				prev_y = curr_y;
			#endif
			}
		}

        set_bnd2d(1, x, sizeX, sizeY);
        set_bnd2d(2, y, sizeX, sizeY);
    }
}

static void diffuse2d(const int b, float * x, const float * x0, const float diff, const float dt, const int iter, const int sizeX, const int sizeY, const float voxelSize)
{
	const float a = dt * diff / voxelSize;
	lin_solve2d(b, x, x0, a, 1 + 4 * a, iter, sizeX, sizeY);
}

static void diffuse2d_xy(float * x, const float * x0, float * y, const float * y0, const float diff, const float dt, const int iter, const int sizeX, const int sizeY, const float voxelSize)
{
	const float a = dt * diff / voxelSize;
	lin_solve2d_xy(x, x0, y, y0, a, 1 + 4 * a, iter, sizeX, sizeY);
}

static void project2d(
	float * __restrict velocX,
	float * __restrict velocY,
	float * __restrict p,
	float * __restrict div, const int iter, const int sizeX, const int sizeY)
{
	for (int j = 1; j < sizeY - 1; ++j)
	{
		for (int i = 1; i < sizeX - 1; ++i)
		{
			div[IX_2D(i, j)] =
				-0.25f *
					(
						+ (+ velocX[IX_2D(i+1, j  )] - velocX[IX_2D(i-1, j  )])
						+ (+ velocY[IX_2D(i  , j+1)] - velocY[IX_2D(i  , j-1)])
					);
		}
	}
	
    set_bnd2d(0, div, sizeX, sizeY);
	
    memset(p, 0, sizeX * sizeY * sizeof(float));
	lin_solve2d(0, p, div, 1, 4, iter, sizeX, sizeY);
	
	for (int j = 1; j < sizeY - 1; ++j)
	{
		for (int i = 1; i < sizeX - 1; ++i)
		{
			velocX[IX_2D(i, j)] -= ( p[IX_2D(i+1, j)] - p[IX_2D(i-1, j)] );
			velocY[IX_2D(i, j)] -= ( p[IX_2D(i, j+1)] - p[IX_2D(i, j-1)] );
		}
	}

    set_bnd2d(1, velocX, sizeX, sizeY);
    set_bnd2d(2, velocY, sizeX, sizeY);
}

static void advect2d(const int b, float * d, const float * d0, const float * velocX, const float * velocY, const float in_dt, const int sizeX, const int sizeY, const float voxelSize)
{
	const float dt = in_dt / voxelSize;
	
	const float X_max = sizeX - 1.5f;
	const float Y_max = sizeY - 1.5f;
	
    float ifloat, jfloat;
    int i, j;
	
	for (j = 1, jfloat = 1; j < sizeY - 1; ++j, ++jfloat)
	{
		for (i = 1, ifloat = 1; i < sizeX - 1; ++i, ++ifloat)
		{
			const float tmp1 = dt * velocX[IX_2D(i, j)];
			const float tmp2 = dt * velocY[IX_2D(i, j)];
			
			float x = ifloat - tmp1;
			float y = jfloat - tmp2;
			
			if(x < 0.5f) x = 0.5f;
			if(x > X_max) x = X_max;
			const float i0 = floorf(x);
			
			if(y < 0.5f) y = 0.5f;
			if(y > Y_max) y = Y_max;
			const float j0 = floorf(y);
			
			const float s1 = x    - i0;
			const float s0 = 1.0f - s1;
			const float t1 = y    - j0;
			const float t0 = 1.0f - t1;
			
			const int i0i = i0;
			const int i1i = i0 + 1;
			const int j0i = j0;
			const int j1i = j0 + 1;
			
			//Assert(i0i >= 0 && i0i < N);
			//Assert(i1i >= 0 && i1i < N);
			//Assert(j0i >= 0 && j0i < N);
			//Assert(j1i >= 0 && j1i < N);
			
			d[IX_2D(i, j)] =
				s0 * (t0 * d0[IX_2D(i0i, j0i)] + t1 * d0[IX_2D(i0i, j1i)]) +
				s1 * (t0 * d0[IX_2D(i1i, j0i)] + t1 * d0[IX_2D(i1i, j1i)]);
		}
	}
	
    set_bnd2d(b, d, sizeX, sizeY);
}

//

void FluidCube2d::addDensity(const int x, const int y, const float amount)
{
	if (x < 0 || x >= sizeX ||
		y < 0 || y >= sizeY)
	{
		return;
	}
	
	const int index = IX_2D(x, y);
	
	density[index] += amount;
}

void FluidCube2d::addVelocity(const int x, const int y, const float amountX, const float amountY)
{
	if (x < 0 || x >= sizeX ||
		y < 0 || y >= sizeY)
	{
		return;
	}
	
	const int index = IX_2D(x, y);

	Vx[index] += amountX;
	Vy[index] += amountY;
}

void FluidCube2d::step()
{
	diffuse2d_xy(Vx0.data(), Vx.data(), Vy0.data(), Vy.data(), visc, dt, iter, sizeX, sizeY, voxelSize);
	
	project2d(Vx0.data(), Vy0.data(), Vx.data(), Vy.data(), iter, sizeX, sizeY);
	
	advect2d(1, Vx.data(), Vx0.data(), Vx0.data(), Vy0.data(), dt, sizeX, sizeY, voxelSize);
    advect2d(2, Vy.data(), Vy0.data(), Vx0.data(), Vy0.data(), dt, sizeX, sizeY, voxelSize);
	
	project2d(Vx.data(), Vy.data(), Vx0.data(), Vy0.data(), iter, sizeX, sizeY);
	
	diffuse2d(0, s.data(), density.data(), diff, dt, iter, sizeX, sizeY, voxelSize);
	
	advect2d(0, density.data(), s.data(), Vx.data(), Vy.data(), dt, sizeX, sizeY, voxelSize);
}

//

FluidCube2d * createFluidCube2d(const int sizeX, const int sizeY, const float diffusion, const float viscosity, const float dt)
{
	FluidCube2d * cube = new FluidCube2d();

	cube->sizeX = sizeX;
	cube->sizeY = sizeY;
	cube->dt = dt;
	cube->diff = diffusion;
	cube->visc = viscosity;

	const int N = sizeX * sizeY;

	cube->s.resize(N, 0.f);
	cube->density.resize(N, 0.f);

	cube->Vx.resize(N, 0.f);
	cube->Vy.resize(N, 0.f);

	cube->Vx0.resize(N, 0.f);
	cube->Vy0.resize(N, 0.f);

	return cube;
}
