#ifndef PROTOCOLS_H
#define PROTOCOLS_H
#pragma once

#include "NetProtocols.h"

enum MYPROTOCOLS
{
	PROTOCOL_INPUT = PROTOCOL_CUSTOM,
	PROTOCOL_REPLICATION,
	PROTOCOL_SCENE
};

#define INPUTMSG_ACTION 1
#define INPUTMSG_ACTION_LOCAL 2
#define INPUTMSG_SETCONTROLLER 4

#define REPMSG_CREATE      1
#define REPMSG_DESTROY     2
#define REPMSG_UPDATE      3

#define SCENEMSG_ACTIVATE 0
#define SCENEMSG_SETCONTROLLER 1
#define SCENEMSG_ENTITY_MESSAGE 2

#endif
