#pragma once

#include "Options.h"

#define GFX_SX 1920
#define GFX_SY 1080

#define NUM_VOTING_BUTTONS 4

OPTION_DECLARE(int, VOTING_CHAR_WIDTH, 80);
OPTION_DECLARE(int, VOTING_CHAR_HEIGHT, 200);

OPTION_DECLARE(int, VOTING_CHAR1_X, 0);
OPTION_DECLARE(int, VOTING_CHAR1_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR2_X, 150);
OPTION_DECLARE(int, VOTING_CHAR2_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR3_X, 300);
OPTION_DECLARE(int, VOTING_CHAR3_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR4_X, 450);
OPTION_DECLARE(int, VOTING_CHAR4_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR5_X, 600);
OPTION_DECLARE(int, VOTING_CHAR5_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR6_X, 750);
OPTION_DECLARE(int, VOTING_CHAR6_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR7_X, 900);
OPTION_DECLARE(int, VOTING_CHAR7_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR8_X, 1050);
OPTION_DECLARE(int, VOTING_CHAR8_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR9_X, 1200);
OPTION_DECLARE(int, VOTING_CHAR9_Y, 0);

OPTION_DECLARE(int, VOTING_CHAR10_X, 1350);
OPTION_DECLARE(int, VOTING_CHAR10_Y, 0);

//

OPTION_DECLARE(int, VOTING_AGENDA_TEXTBOX_X, 70);
OPTION_DECLARE(int, VOTING_AGENDA_TEXTBOX_Y, 150);
OPTION_DECLARE(int, VOTING_AGENDA_TEXTBOX_WIDTH, 750);
OPTION_DECLARE(int, VOTING_AGENDA_TEXTBOX_HEIGHT, 280);

//

OPTION_DECLARE(int, VOTING_CHAR_X, 1150);
OPTION_DECLARE(int, VOTING_CHAR_Y, 20);

OPTION_DECLARE(int, VOTING_GOAL_X, 1150);
OPTION_DECLARE(int, VOTING_GOAL_Y, 280);

OPTION_DECLARE(int, VOTING_STAT_FOOD_X, 1550);
OPTION_DECLARE(int, VOTING_STAT_FOOD_Y, 20);
OPTION_DECLARE(int, VOTING_STAT_WEALTH_X, 1550);
OPTION_DECLARE(int, VOTING_STAT_WEALTH_Y, 120);
OPTION_DECLARE(int, VOTING_STAT_TECH_X, 1800);
OPTION_DECLARE(int, VOTING_STAT_TECH_Y, 20);
OPTION_DECLARE(int, VOTING_STAT_HAPPINESS_X, 1800);
OPTION_DECLARE(int, VOTING_STAT_HAPPINESS_Y, 120);

//

OPTION_DECLARE(int, VOTING_OPTION_X, 75);
OPTION_DECLARE(int, VOTING_OPTION_Y, 470);
OPTION_DECLARE(int, VOTING_OPTION_DY, 120);
OPTION_DECLARE(int, VOTING_OPTION_BUTTON_SIZE, 100);

//

OPTION_DECLARE(int, VOTING_TARGET_CHAR1_X, 0);
OPTION_DECLARE(int, VOTING_TARGET_CHAR1_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR2_X, 100);
OPTION_DECLARE(int, VOTING_TARGET_CHAR2_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR3_X, 200);
OPTION_DECLARE(int, VOTING_TARGET_CHAR3_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR4_X, 300);
OPTION_DECLARE(int, VOTING_TARGET_CHAR4_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR5_X, 400);
OPTION_DECLARE(int, VOTING_TARGET_CHAR5_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR6_X, 500);
OPTION_DECLARE(int, VOTING_TARGET_CHAR6_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR7_X, 600);
OPTION_DECLARE(int, VOTING_TARGET_CHAR7_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR8_X, 700);
OPTION_DECLARE(int, VOTING_TARGET_CHAR8_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR9_X, 800);
OPTION_DECLARE(int, VOTING_TARGET_CHAR9_Y, 100);

OPTION_DECLARE(int, VOTING_TARGET_CHAR10_X, 900);
OPTION_DECLARE(int, VOTING_TARGET_CHAR10_Y, 100);
