void main(
	in float4 in_position : POSITION,
	in float4 in_texcoord : TEXCOORD0,
	in float4 in_size : TEXCOORD1,
	in const uniform float4x4 wv,
	in const uniform float4x4 p,
	out float4 out_position : POSITION,
	out float4 out_texcoord : TEXCOORD0)
{
	float4 position = mul(in_position, wv);

	position += float4(in_size.xy, 0.0f, 0.0f);

	out_position = mul(position, p);
	out_texcoord = in_texcoord;
}
